stmt = if | while | (func | declare | expr) ';';

if      = 'if' '(' expr ')' block [ 'else' block ];
func    = 'define' id '(' fargs ')' '=' expr;
while   = 'while' '(' expr ')' block;
declare = modifer id '=' expr;

block = '{' [{ stmt }] '}';

fact = literal | brackets | call;

call     = id '(' cargs ')';
literal  = id | num;
brackets = '(' expr ')';

fargs = [  id  { ','  id  } ];
cargs = [ expr { ',' expr } ];