code = { stmt ';' }

stmt = function | assign | call;

function = 'define' id '(' id ')' '=' expr;
assign = id '=' expr;
call = id '(' expr ')';

expr = term { a term };
term = fact { b fact }; 
fact = num | id | '-' fact | call | '(' expr ')';